services:
  dreamjournal:
    image: georgepapagapitos/dreamjournal:latest
    container_name: dreamjournal
    restart: unless-stopped
    networks:
      - nginxproxymanager_default
    ports:
      - "8765:8000"
    volumes:
      - ./data:/data
    environment:
      - DB_PATH=/data/dreams.db
      - TZ=America/Chicago

networks:
  nginxproxymanager_default:
    external: true